name: MeowServerTP
main: com.meowstp.MeowServerTP
version: 1.0.0
api-version: 1.16
depend:
  - MeowLibs
commands:
  mstp:
    description: Cross-server teleport command
    usage: /mstp tp <server> | /mstp send <player> <server>
    permission: meowservertp.command.mstp
permissions:
  meowservertp.command.mstp:
    description: /mstp
    default: true
  meowservertp.command.send:
    description: /mstp send
    default: op